//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante_reservas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_Cliente { get; set; }
        public int id_Estado { get; set; }
        public int cantidad_personas { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
